"""add conferência documental fields

Revision ID: ecf042e679b9
Revises: fe1823cbdd2f
Create Date: 2025-07-18 14:12:55.150032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf042e679b9'
down_revision = 'fe1823cbdd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linha_producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rg_cpf_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comp_residencia_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cert_nasc_casamento_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requerimento_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dtc_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negativa_pad_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contracheque_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('declaracao_chefia_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('termo_subsidio_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('declaracao_bens_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('extrato_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qd_elevacao_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lotacao_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tempo_contribuicao_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('anexos_tce_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('portaria_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fixacao_o_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('siarhes_doc', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linha_producao', schema=None) as batch_op:
        batch_op.drop_column('siarhes_doc')
        batch_op.drop_column('fixacao_o_doc')
        batch_op.drop_column('portaria_doc')
        batch_op.drop_column('anexos_tce_doc')
        batch_op.drop_column('tempo_contribuicao_doc')
        batch_op.drop_column('lotacao_doc')
        batch_op.drop_column('qd_elevacao_doc')
        batch_op.drop_column('extrato_doc')
        batch_op.drop_column('declaracao_bens_doc')
        batch_op.drop_column('termo_subsidio_doc')
        batch_op.drop_column('declaracao_chefia_doc')
        batch_op.drop_column('contracheque_doc')
        batch_op.drop_column('negativa_pad_doc')
        batch_op.drop_column('dtc_doc')
        batch_op.drop_column('requerimento_doc')
        batch_op.drop_column('cert_nasc_casamento_doc')
        batch_op.drop_column('comp_residencia_doc')
        batch_op.drop_column('rg_cpf_doc')

    # ### end Alembic commands ###
