"""initial schema

Revision ID: fe1823cbdd2f
Revises: 
Create Date: 2025-07-17 13:10:50.484455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1823cbdd2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=True),
    sa.Column('primeiro_acesso_realizado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('linha_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=20), nullable=False),
    sa.Column('semana', sa.String(length=50), nullable=False),
    sa.Column('indice_linha', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('numero_processo', sa.String(length=100), nullable=True),
    sa.Column('nome_do_segurado', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('homologacao', sa.Boolean(), nullable=True),
    sa.Column('diligencia', sa.Boolean(), nullable=True),
    sa.Column('fixacao_civil', sa.Boolean(), nullable=True),
    sa.Column('conf_civil', sa.Boolean(), nullable=True),
    sa.Column('registro_civil', sa.Boolean(), nullable=True),
    sa.Column('fixacao_pensao', sa.Boolean(), nullable=True),
    sa.Column('conf_pensao', sa.Boolean(), nullable=True),
    sa.Column('in_68', sa.Boolean(), nullable=True),
    sa.Column('outros', sa.Boolean(), nullable=True),
    sa.Column('resolucao', sa.Text(), nullable=True),
    sa.Column('removido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linha_producao')
    op.drop_table('usuario')
    # ### end Alembic commands ###
